apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-basic-example.fullname" . }}
  labels:
    helm.sh/chart: {{ include "helm-basic-example.chart" . }}
    app.kubernetes.io/name: {{ include "helm-basic-example.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "helm-basic-example.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: NodePort
  ports:
  - protocol: TCP
    targetPort: 80
    port: 80
# ---
#   apiVersion: extensions/v1beta1
#   kind: Ingress
#   metadata:
#     name: example-ingress
#     annotations:
#       ingress.kubernetes.io/rewrite-target: /
#   spec:
#     rules:
#     - http:
#         paths:
#         - path: /
#           backend:
#             serviceName: {{ include "helm-basic-example.fullname" . }}
#             servicePort: 80
#         - path: /bar
#           backend:
#             serviceName: bar-service
#             servicePort: 80
# # ---